import { getBaseUrl } from '@/lib/metadata';

type SmtpConfig = {
  host?: string;
  port?: number;
  secure?: boolean;
  user?: string;
  pass?: string;
  from?: string;
  to?: string;
};

function getConfig(): SmtpConfig {
  return {
    host: process.env.SMTP_HOST,
    port: process.env.SMTP_PORT ? Number(process.env.SMTP_PORT) : undefined,
    secure: String(process.env.SMTP_SECURE || '').toLowerCase() === 'true',
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
    from: process.env.MAIL_FROM,
    to: process.env.MAIL_TO || process.env.CONTACT_TO
  };
}

let transporter: any | null = null;

export async function getTransporter() {
  if (transporter) return transporter;
  const cfg = getConfig();
  if (!cfg.host || !cfg.port || !cfg.user || !cfg.pass) return null;
  // Lazy-load nodemailer to avoid bundling it into Next vendor chunks unnecessarily
  const nodemailer = (await import('nodemailer')).default;
  transporter = nodemailer.createTransport({
    host: cfg.host,
    port: cfg.port,
    secure: cfg.secure,
    auth: { user: cfg.user, pass: cfg.pass }
  });
  return transporter;
}

async function getDict(locale?: 'en'|'fa') {
  try {
    return locale === 'fa' ? (await import('@/locales/fa/common.json')).default : (await import('@/locales/en/common.json')).default;
  } catch {
    return {} as any;
  }
}

export async function sendContactEmail(input: { name: string; email: string; phone: string; subject?: string; message: string; locale?: 'en'|'fa' }) {
  const tx = await getTransporter();
  const cfg = getConfig();
  if (!tx || !cfg.to) return false;

  const dict = await getDict(input.locale);
  const emailTitle = (dict as any).email_new_contact_title || 'New contact message';
  const submittedVia = (dict as any).email_submitted_via_contact || 'Submitted via contact form';
  const nameLabel = (dict as any).name_label || 'Name';
  const emailLabel = (dict as any).email_label || 'Email';
  const phoneLabel = (dict as any).phone_label || 'Phone';
  const subjectLabel = (dict as any).subject_label || 'Subject';
  const localeLabel = (dict as any).locale_label || 'Locale';
  const messageLabel = (dict as any).message_label || 'Message';
  const footerText = (dict as any).email_footer_generated || 'This email was generated by the website contact form.';

  const subject = input.subject && input.subject.trim().length > 0 ? input.subject : `${emailTitle}${input.locale ? ' (' + input.locale + ')' : ''}`;
  const from = cfg.from || cfg.user!;
  const text = `Name: ${input.name}\nEmail: ${input.email}\nPhone: ${input.phone}\nLocale: ${input.locale || ''}\n---\n${input.message}`;

  const base = getBaseUrl();
  const brand = process.env.MAIL_BRAND || 'IEEE Student Branch - Quchan University of Technology';
  const logoUrl = `${base}/icon.png`;
  const html = `
  <div style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Arial,'Noto Sans',sans-serif;color:#111;line-height:1.6;background:#f7f7fb;padding:24px">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;border:1px solid #e9e9f3">
      <tr>
        <td style="padding:16px 20px;background:linear-gradient(135deg,rgba(126,87,194,0.2),rgba(82,168,255,0.2))">
          <table width="100%" cellspacing="0" cellpadding="0" role="presentation">
            <tr>
              <td style="vertical-align:middle"><img src="${logoUrl}" alt="logo" height="28" style="display:block"></td>
              <td style="text-align:right;font-weight:700;font-size:14px;color:#17223b">${escapeHtml(brand)}</td>
            </tr>
          </table>
        </td>
      </tr>
      <tr>
        <td style="padding:20px 20px 8px 20px">
          <h2 style="margin:0 0 8px 0;font-size:18px;color:#111">${escapeHtml(emailTitle)}</h2>
          <p style="margin:0;color:#666;font-size:13px">${escapeHtml(submittedVia)}</p>
        </td>
      </tr>
      <tr>
        <td style="padding:8px 20px 0 20px">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="6" style="border-collapse:separate;border-spacing:0 8px">
            <tr>
              <td style="width:140px;color:#555;background:#f5f6fa;border:1px solid #eceef6;border-right:none;border-radius:8px 0 0 8px;padding:8px 10px">${escapeHtml(nameLabel)}</td>
              <td style="border:1px solid #eceef6;border-left:none;border-radius:0 8px 8px 0;padding:8px 10px">${escapeHtml(input.name)}</td>
            </tr>
            <tr>
              <td style="width:140px;color:#555;background:#f5f6fa;border:1px solid #eceef6;border-right:none;border-radius:8px 0 0 8px;padding:8px 10px">${escapeHtml(emailLabel)}</td>
              <td style="border:1px solid #eceef6;border-left:none;border-radius:0 8px 8px 0;padding:8px 10px">${escapeHtml(input.email)}</td>
            </tr>
            <tr>
              <td style="width:140px;color:#555;background:#f5f6fa;border:1px solid #eceef6;border-right:none;border-radius:8px 0 0 8px;padding:8px 10px">${escapeHtml(phoneLabel)}</td>
              <td style="border:1px solid #eceef6;border-left:none;border-radius:0 8px 8px 0;padding:8px 10px">${escapeHtml(input.phone)}</td>
            </tr>
            ${input.subject ? `<tr>
              <td style="width:140px;color:#555;background:#f5f6fa;border:1px solid #eceef6;border-right:none;border-radius:8px 0 0 8px;padding:8px 10px">${escapeHtml(subjectLabel)}</td>
              <td style="border:1px solid #eceef6;border-left:none;border-radius:0 8px 8px 0;padding:8px 10px">${escapeHtml(input.subject)}</td>
            </tr>` : ''}
            ${input.locale ? `<tr>
              <td style="width:140px;color:#555;background:#f5f6fa;border:1px solid #eceef6;border-right:none;border-radius:8px 0 0 8px;padding:8px 10px">${escapeHtml(localeLabel)}</td>
              <td style="border:1px solid #eceef6;border-left:none;border-radius:0 8px 8px 0;padding:8px 10px">${escapeHtml(input.locale!)}</td>
            </tr>` : ''}
          </table>
        </td>
      </tr>
      <tr>
        <td style="padding:12px 20px 20px 20px">
          <div style="border:1px solid #eceef6;border-radius:8px;padding:12px">
            <div style="font-size:12px;color:#666;margin-bottom:8px">${escapeHtml(messageLabel)}</div>
            <div style="white-space:pre-wrap;font-family:inherit;font-size:14px;color:#111">${escapeHtml(input.message)}</div>
          </div>
        </td>
      </tr>
      <tr>
        <td style="padding:10px 20px 20px 20px;color:#9aa4b2;font-size:12px">${escapeHtml(footerText)}</td>
      </tr>
    </table>
  </div>`;
  await tx.sendMail({ from, to: cfg.to, subject, text, html });
  return true;
}

function escapeHtml(s: string) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export async function sendEmailVerificationEmail(input: { email: string; name?: string; token: string; locale?: 'en'|'fa' }) {
  const tx = await getTransporter();
  const cfg = getConfig();
  if (!tx) {
    console.warn('[mailer] No email transporter configured; skipping verification email send.', { email: input.email });
    return true;
  }
  const dict = await getDict(input.locale);
  const base = getBaseUrl();
  const locale = input.locale === 'fa' ? 'fa' : 'en';
  const verifyUrl = `${base}/${locale}/verify-email?token=${encodeURIComponent(input.token)}`;
  const subject = (dict as any).email_verify_subject || 'Verify your email address';
  const title = (dict as any).email_verify_title || 'Confirm your email';
  const cta = (dict as any).email_verify_cta || 'Verify Email';
  const hint = (dict as any).email_verify_hint || 'This link expires in 24 hours.';
  const ignore = (dict as any).email_verify_ignore || 'If you did not request this, please ignore this email.';
  const greetingLabel = (dict as any).email_greeting || 'Hello';
  const brand = process.env.MAIL_BRAND || 'IEEE Student Branch - Quchan University of Technology';
  const from = cfg.from || cfg.user!;
  const text = `${greetingLabel} ${input.name || ''}\n\n${title}\n${verifyUrl}\n\n${hint}\n${ignore}`;
  const html = `
  <div style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Arial,'Noto Sans',sans-serif;color:#111;line-height:1.6;background:#f7f7fb;padding:24px">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;border:1px solid #e9e9f3">
      <tr>
        <td style="padding:16px 20px;background:linear-gradient(135deg,rgba(126,87,194,0.2),rgba(82,168,255,0.2))">
          <table width="100%" cellspacing="0" cellpadding="0" role="presentation">
            <tr>
              <td style="vertical-align:middle"><img src="${base}/icon.png" alt="logo" height="28" style="display:block"></td>
              <td style="text-align:right;font-weight:700;font-size:14px;color:#17223b">${escapeHtml(brand)}</td>
            </tr>
          </table>
        </td>
      </tr>
      <tr>
        <td style="padding:20px 20px 0 20px;font-size:14px;color:#555">${escapeHtml(greetingLabel)} ${escapeHtml(input.name || '')}</td>
      </tr>
      <tr>
        <td style="padding:12px 20px 0 20px">
          <h2 style="margin:0;font-size:20px;color:#111">${escapeHtml(title)}</h2>
        </td>
      </tr>
      <tr>
        <td style="padding:12px 20px">
          <p style="margin:0 0 16px 0;color:#555;font-size:14px">${escapeHtml(hint)}</p>
          <a href="${verifyUrl}" style="display:inline-block;padding:12px 20px;background:#4f46e5;color:#fff;font-weight:600;border-radius:8px;text-decoration:none">${escapeHtml(cta)}</a>
          <p style="margin:16px 0 0 0;color:#999;font-size:12px">${escapeHtml(verifyUrl)}</p>
        </td>
      </tr>
      <tr>
        <td style="padding:0 20px 20px 20px;color:#9aa4b2;font-size:12px">${escapeHtml(ignore)}</td>
      </tr>
    </table>
  </div>`;
  try {
    await tx.sendMail({ from, to: input.email, subject, text, html });
    console.info('[mailer] Sent verification email', { email: input.email, locale });
    return true;
  } catch (err) {
    console.error('[mailer] Failed to send verification email', { email: input.email, locale, error: err instanceof Error ? err.message : err });
    return false;
  }
}

export async function sendPasswordResetEmail(input: { email: string; name?: string; token: string; locale?: 'en'|'fa' }) {
  const tx = await getTransporter();
  const cfg = getConfig();
  if (!tx) {
    console.warn('[mailer] No email transporter configured; skipping password reset email.', { email: input.email });
    return true;
  }
  const dict = await getDict(input.locale);
  const base = getBaseUrl();
  const locale = input.locale === 'fa' ? 'fa' : 'en';
  const resetUrl = `${base}/${locale}/reset-password?token=${encodeURIComponent(input.token)}`;
  const subject = (dict as any).password_reset_subject || 'Reset your password';
  const title = (dict as any).password_reset_title || 'Reset your password';
  const cta = (dict as any).password_reset_cta || 'Reset password';
  const info = (dict as any).password_reset_hint || 'This link expires soon. If you did not request it, ignore this email.';
  const greetingLabel = (dict as any).email_greeting || 'Hello';
  const brand = process.env.MAIL_BRAND || 'IEEE Student Branch - Quchan University of Technology';
  const from = cfg.from || cfg.user!;
  const text = `${greetingLabel} ${input.name || ''}\n\n${title}\n${resetUrl}\n\n${info}`;
  const html = `
  <div style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Arial,'Noto Sans',sans-serif;color:#111;line-height:1.6;background:#f7f7fb;padding:24px">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;border:1px solid #e9e9f3">
      <tr>
        <td style="padding:16px 20px;background:linear-gradient(135deg,rgba(244,114,182,0.2),rgba(14,165,233,0.2))">
          <table width="100%" cellspacing="0" cellpadding="0" role="presentation">
            <tr>
              <td style="vertical-align:middle"><img src="${base}/icon.png" alt="logo" height="28" style="display:block"></td>
              <td style="text-align:right;font-weight:700;font-size:14px;color:#17223b">${escapeHtml(brand)}</td>
            </tr>
          </table>
        </td>
      </tr>
      <tr>
        <td style="padding:20px 20px 0 20px;font-size:14px;color:#555">${escapeHtml(greetingLabel)} ${escapeHtml(input.name || '')}</td>
      </tr>
      <tr>
        <td style="padding:12px 20px 0 20px">
          <h2 style="margin:0;font-size:20px;color:#111">${escapeHtml(title)}</h2>
        </td>
      </tr>
      <tr>
        <td style="padding:12px 20px">
          <p style="margin:0 0 16px 0;color:#555;font-size:14px">${escapeHtml(info)}</p>
          <a href="${resetUrl}" style="display:inline-block;padding:12px 20px;background:#0f766e;color:#fff;font-weight:600;border-radius:8px;text-decoration:none">${escapeHtml(cta)}</a>
          <p style="margin:16px 0 0 0;color:#999;font-size:12px">${escapeHtml(resetUrl)}</p>
        </td>
      </tr>
    </table>
  </div>`;
  try {
    await tx.sendMail({ from, to: input.email, subject, text, html });
    console.info('[mailer] Sent password reset email', { email: input.email, locale });
    return true;
  } catch (err) {
    console.error('[mailer] Failed to send password reset email', { email: input.email, locale, error: err instanceof Error ? err.message : err });
    return false;
  }
}

export async function sendNotificationEmail(input: { email: string; name?: string; title: string; body: string; type: string; locale?: 'en'|'fa' }) {
  const tx = await getTransporter();
  const cfg = getConfig();
  if (!tx) {
    console.warn('[mailer] No email transporter configured; skipping notification email.', { email: input.email });
    return true;
  }
  const dict = await getDict(input.locale);
  const greetingLabel = (dict as any).email_greeting || 'Hello';
  const footerText = (dict as any).notification_email_footer || 'You are receiving this notification because of recent activity on your account.';
  const subject = `${(dict as any).notification_email_subject || 'Notification'} – ${input.title}`;
  const brand = process.env.MAIL_BRAND || 'IEEE Student Branch - Quchan University of Technology';
  const from = cfg.from || cfg.user!;
  const text = `${greetingLabel} ${input.name || ''}\n\n${input.title}\n${input.body}\n\n${footerText}`;
  const html = `
  <div style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Arial,'Noto Sans',sans-serif;color:#111;line-height:1.6;background:#f7f7fb;padding:24px">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;border:1px solid #e9e9f3">
      <tr>
        <td style="padding:16px 20px;background:linear-gradient(135deg,rgba(99,102,241,0.2),rgba(56,189,248,0.2))">
          <table width="100%" cellspacing="0" cellpadding="0" role="presentation">
            <tr>
              <td style="vertical-align:middle"><img src="${getBaseUrl()}/icon.png" alt="logo" height="28" style="display:block"></td>
              <td style="text-align:right;font-weight:700;font-size:14px;color:#17223b">${escapeHtml(brand)}</td>
            </tr>
          </table>
        </td>
      </tr>
      <tr>
        <td style="padding:20px 20px 0 20px;font-size:14px;color:#555">${escapeHtml(greetingLabel)} ${escapeHtml(input.name || '')}</td>
      </tr>
      <tr>
        <td style="padding:12px 20px 0 20px">
          <h2 style="margin:0;font-size:20px;color:#111">${escapeHtml(input.title)}</h2>
        </td>
      </tr>
      <tr>
        <td style="padding:12px 20px">
          <p style="margin:0;color:#555;font-size:14px;white-space:pre-wrap">${escapeHtml(input.body)}</p>
        </td>
      </tr>
      <tr>
        <td style="padding:16px 20px 20px 20px;color:#9aa4b2;font-size:12px">${escapeHtml(footerText)}</td>
      </tr>
    </table>
  </div>`;
  try {
    await tx.sendMail({ from, to: input.email, subject, text, html });
    console.info('[mailer] Sent notification email', { email: input.email, type: input.type });
    return true;
  } catch (err) {
    console.error('[mailer] Failed to send notification email', { email: input.email, type: input.type, error: err instanceof Error ? err.message : err });
    return false;
  }
}
